import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from 'next';
import { Inter, Figtree } from 'next/font/google';
import './globals.css';
import BootstrapClient from '@/components/BootstrapClient';
import ModalProvider from '@/providers/ModalProvider';

const font = Figtree({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Cool Notes App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ModalProvider />
        <BootstrapClient>{children}</BootstrapClient>
      </body>
    </html>
  );
}
